server:
  port: 8080
spring:
  application:
    #应用的名称
    name: reggie_take_out
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/reggie?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: root
    # 邮箱配置
  mail:
    host: smtp.qq.com  # 发送邮件的服务器地址
    username: 1506523471@qq.com # 开启 IMAP/SMTP服务 的qq邮箱的账号
    password: knfxsyaizhbwbagi  # 开启 IMAP/SMTP服务 获得的授权码,而不是qq邮箱的登录密码
    default-encoding: UTF-8

mybatis-plus:
  configuration:
    # 在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    # 配置控制台打印完整带参数SQL语句
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # MyBatis-Plus的ID生成算法的配置方式:
  global-config:
    db-config:
      id-type: ASSIGN_ID
reggie:
  path: F:\SpringBoot_project\Reggie\code\images\